# Generated by Django 3.0.6 on 2020-06-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Titulo del servicio')),
                ('status', models.BooleanField(default=True, verbose_name='activado/desactivado')),
                ('image', models.ImageField(upload_to='service <django.db.models.fields.CharField>')),
            ],
        ),
    ]
