# Generated by Django 3.0.6 on 2020-06-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200606_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True, verbose_name='activado/desactivado')),
                ('content', models.CharField(max_length=800, verbose_name='Contenido')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('position', models.CharField(max_length=100, verbose_name='Cargo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
    ]
