# Generated by Django 3.0.6 on 2020-06-08 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200608_2014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'verbose_name': 'Testimonio', 'verbose_name_plural': 'Testimonios'},
        ),
    ]
